# Generated by Django 5.0.1 on 2024-01-11 14:47

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued', models.DateField(verbose_name='when the crew was created')),
                ('foreman', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100, verbose_name='where is the emergency')),
                ('date', models.DateField(default=datetime.datetime(2024, 1, 11, 14, 47, 53, 93252), verbose_name='when the emergency was issued')),
                ('duration', models.DurationField(default=datetime.date(2024, 1, 11), verbose_name='time needed to resolve the emergency')),
            ],
        ),
        migrations.CreateModel(
            name='CrewMate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('rank', models.CharField()),
                ('crew_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mission_control.crew')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=50, verbose_name='slang name')),
                ('vehicle_index', models.CharField(max_length=50, verbose_name='coded Name')),
                ('max_crew', models.IntegerField(verbose_name='max # crew')),
                ('tot_km', models.IntegerField(verbose_name='total KM for vehicle')),
                ('in_operation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mission_control.mission')),
            ],
        ),
        migrations.AddField(
            model_name='crew',
            name='service_veichle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mission_control.vehicle'),
        ),
    ]
