# Generated by Django 5.0.1 on 2024-01-11 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 1, 11, 14, 49, 12, 34405, tzinfo=datetime.timezone.utc), verbose_name='when the emergency was issued'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='duration',
            field=models.DurationField(default=datetime.datetime(2024, 1, 11, 14, 49, 12, 34447, tzinfo=datetime.timezone.utc), verbose_name='time needed to resolve the emergency'),
        ),
    ]
