# Generated by Django 5.0.1 on 2024-01-11 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission_control', '0002_alter_mission_date_alter_mission_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='issued',
            field=models.DateField(default=datetime.datetime(2024, 1, 11, 14, 49, 47, 350970, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='mission',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 1, 11, 14, 49, 47, 350388, tzinfo=datetime.timezone.utc), verbose_name='when the emergency was issued'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='duration',
            field=models.DurationField(default=datetime.datetime(2024, 1, 11, 14, 49, 47, 350411, tzinfo=datetime.timezone.utc), verbose_name='time needed to resolve the emergency'),
        ),
    ]
