# Generated by Django 5.0.1 on 2024-01-11 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission_control', '0003_alter_crew_issued_alter_mission_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='issued',
            field=models.DateField(verbose_name=datetime.datetime(2024, 1, 11, 14, 50, 1, 302236, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='mission',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 1, 11, 14, 50, 1, 301694, tzinfo=datetime.timezone.utc), verbose_name='when the emergency was issued'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='duration',
            field=models.DurationField(default=datetime.datetime(2024, 1, 11, 14, 50, 1, 301714, tzinfo=datetime.timezone.utc), verbose_name='time needed to resolve the emergency'),
        ),
    ]
