# Generated by Django 5.0.1 on 2024-01-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission_control', '0004_alter_crew_issued_alter_mission_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='issued',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='mission',
            name='date',
            field=models.DateField(verbose_name='when the emergency was issued'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='duration',
            field=models.DurationField(verbose_name='time needed to resolve the emergency'),
        ),
    ]
