# Generated by Django 5.0.1 on 2024-01-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission_control', '0005_alter_crew_issued_alter_mission_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crew',
            name='service_veichle',
        ),
        migrations.AddField(
            model_name='crew',
            name='service_vehicle',
            field=models.CharField(default='blank'),
        ),
    ]
